language: generic

env:
  global:
    - MPI=mpich2
    - F77=gfortran-5
#  - MPI=openmpi
# Open MPI is disabled until there is a way to install a reasonably recent
# version, as 1.6.5 is known to have bugs that lead to incorrect behavior in
# Elemental for complex data despite attempts at performing soft casts
# to twice as many entries of real data (with the exact cause unfortunately
# currently unknown)
  matrix:
    - CC=gcc-5 CXX=g++-5
    - CC=clang-3.8 CXX=clang++-3.8

notifications:
  email: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.8 main'
        key_url: http://apt.llvm.org/llvm-snapshot.gpg.key
    packages:
      - gcc-5
      - g++-5
      - gfortran-5
      - libstdc++-5-dev
      - clang-3.8

install:
  - sh travis/install-mpi.sh $MPI
  - curl https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz | sudo tar -x -z --strip-components 1 -C /usr

before_script:
  - sudo hostname localhost

script:
  - mkdir build && cd build;
    cmake -DEL_TESTS=ON -DEL_EXAMPLES=ON -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC -DCMAKE_Fortran_COMPILER=$F77 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/Install .. ;
    if test $? -ne 0; then cat CMakeFiles/CMakeError.log; fi
  - make -j2 && sudo make install && sudo ctest --output-on-failure

